config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, controllers: {
    sessions: "customer/devises/sessions",
    passwords: "customer/devises/passwords",
    registrations: "customer/devises/registrations",
  }


  devise_for :admins, controllers: {
    sessions: "admin/devises/sessions",
    passwords: "admin/devises/passwords",
    registrations: "admin/devises/registrations",
  }


  root 'customer/homes#top'


  get 'homes/about' => 'customer/homes#about', as: 'about'
  get 'homes/party' => 'customer/homes#party', as: 'party'
  get 'homes/wedding' => 'customer/homes#wedding', as: 'wedding'
  get 'inquiries/complete' => 'customer/inquiries#complete', as: 'inquiries_complete'
  post 'reservations/confirm' => 'customer/reservations#confirm', as: 'reservations_confirm'
  get 'reservations/complete' => 'customer/reservations#complete', as: 'reservations_complete'


  get 'admins/home/top' => 'admin/homes#top', as: 'admin_top'


  scope module: :customer do
    resources :customers, only: [:show, :edit, :update, :destroy]
    resources :reservations, only: [:new, :index, :create, :destroy]
    resources :topics, only: [:index, :show] do
  	  resource :favorites, only: [:create, :destroy]
  	  resources :comments, only: [:create, :destroy]
    end
  end


  namespace :admin do
    resources :topics, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :inquiries, only: [:index, :show]
    resources :reservations, only: [:index, :show]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController


  before_action :authenticate_admin!


  def top
    range = Date.today.beginning_of_day..Date.today.end_of_day
    @inquirie = Inquirie.where(created_at: range)
    @reservation = Reservation.where(created_at: range)
  end


end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController


  def create
  	topic = Topic.find(params[:topic_id])
    comment = current_customer.comments.new(comment_params)
    comment.topic_id = topic.id
    comment.save
    redirect_back(fallback_location: root_path)
  end


  def destroy
    @comment = Comment.find(params[:topic_id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end




  private

    def comment_params
      params.require(:comment).permit(:comment)
    end
    

    def correct_customer
      customer = Comment.find(params[:id])
      unless current_customer.id == customer.id
         redirect_to topic_path
      end
    end

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController


  def show
  	@customer = Customer.find(current_customer.id)
  end


  def edit
  	@customer = Customer.find(current_customer.id)
  end


  def update
  	@customer = Customer.find(current_customer.id)
    if @customer.update(customer_params)
      redirect_to customer_path
    else
      render :edit
    end
  end




  private

    def customer_params
      params.require(:customer).permit(:name, :email, :password)
    end



end

app/controllers/customer/devises/confirmations_controller.rb
# frozen_string_literal: true

class Customer::Devises::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/devises/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::Devises::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/devises/passwords_controller.rb
# frozen_string_literal: true

class Customer::Devises::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/devises/registrations_controller.rb
# frozen_string_literal: true

class Customer::Devises::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


  def show
  end


end

app/controllers/customer/devises/sessions_controller.rb
# frozen_string_literal: true

class Customer::Devises::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/devises/unlocks_controller.rb
# frozen_string_literal: true

class Customer::Devises::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController


  def create
  	topic = Topic.find(params[:topic_id])
    favorite = current_customer.favorites.new(topic_id: topic.id)
    favorite.save
    redirect_to topic_path(topic)
  end


  def destroy
  	topic = Topic.find(params[:topic_id])
    favorite = current_customer.favorites.find_by(topic_id: topic.id)
    favorite.destroy
    redirect_to topic_path(topic)
  end


end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController


  def top
  	@topic = Topic.find_by(title: "新型コロナウイルス等の感染予防対策について")
    @topics = Topic.all.order(created_at: :desc)
  end


end

app/controllers/customer/inquiries_controller.rb
class Customer::InquiriesController < ApplicationController


  before_action :authenticate_customer!


  def new
  end


  def create
  end


  def confirm
  end




  private

    def inquirie_params
      params.require(:inquirie).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :tel, :email, :body)
    end


end

app/controllers/customer/reservations_controller.rb
class Customer::ReservationsController < ApplicationController


  before_action :authenticate_customer!


  def new
    @reservation = Reservation.new
  end


  def index
  end


  def confirm
    @reservation = Reservation.new
  end


  def create
    @reservation = current_customer.reservations.create(reservation_params)
    if @reservation.save
      redirect_to reservations_complete_path
      flash[:notice] = "予約が完了しました。"
    else
      flash[:alert] = "再度入力してください"
      render :new
    end
  end


  def complete
  end




  private

    def reservation_params
      params.require(:reservation).permit(:customer_id, :first_name, :last_name, :first_name_kana, :last_name_kana, :tel, :email, :people, :date, :time, :body)
    end


end

app/controllers/customer/topics_controller.rb
class Customer::TopicsController < ApplicationController


  def index
  	@topic = Topic.new
    @topics = Topic.all.order(created_at: :desc).page(params[:page])
  end


  def show
  	@topics = Topic.find(params[:id])
  	@comment = Comment.new
  	@comments = @topics.comments
    @topic_new = Topic.new
  end


end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/customer/comments_helper 2.rb
module Customer::CommentsHelper
end

app/helpers/customer/comments_helper.rb
module Customer::CommentsHelper
end

app/helpers/customer/customers_helper 2.rb
module Customer::CustomersHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/customer/homes/about.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">

            <div class="about_img">
                <%= image_tag asset_path('about.jpg'), size: '900x450' %>
            </div>


            <div class="about">

                <h2>Bell Foret</h2>

                <div class="line_jp">
                    料理は愛から始まる芸術です。<br>
                    人を愛し、食材を愛すること。<br>
                    愛情は料理に現れます。<br>
                    私たちシェフが料理をするとき、まず想うこと。<br>
                    それは出来上がった料理をお客様が心より美味しそうに嬉しそうに召し上がってくださる姿です。<br>
                    絵画や映画など人の心を動かす全ての芸術がそうであるように、料理もまた、創造するプロセスに厳しさを伴うもの。<br>
                    時には、不安という壁に閉ざされて、身動きできなくなることもあります。<br>
                    しかし、お客様のその喜びで輝くような笑顔によって支えられ、料理がもたらす愛のメッセージによって励まされ、<br>
                    私たちは常に前に進むことができるのです。<br>
                    今日も私たちのつくる一皿が、皆様に幸せなひとときを贈ることを願って。<br>
                    ボナペティ！
                </div>

                <div class="line_fc">
                    La cuisine est un acte d’Amour, parce que nous l'expérimentons d'abord à l'approbation de ceux susceptibles de la découvrir.<br>
                    C'est pour ça, que la musique comme la peinture,<br>
                    comme tout ce qui est beau, est un Art exigeant qui suppose de notre côté,<br>
                    une régularité, une inquiétude qui n'est réconforté que par le massage d'Amour qu'elle apporte.<br>
                    Si la musique nous transporte dans un message d'Amour, si la peinture, nous réunit dans une admiration universelle, il faut que la cuisine entraîne chez nous une attitude semblable.<br>
                    Bon appétit!
                </div>

            </div>


        </div>
    </div>
</div>

app/views/customer/homes/party.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">


            <div class="row">
                <div class="party_image">
                    <div class="style_party">PARTY</div>
                </div>
            </div>


            <div class="row">

                <h2>フランスの古城を思わせる優雅な個室</h2>

                <div class="line_jp">
        	        シャトーレストランの最上階に位置する個室。<br>
                    大切なお客様のおもてなし、ご家族やご友人との記念日のお祝いなど、様々なシーンにご利用いただけます。<br>
                    ガストロノミー “ Bell Foret ”のお食事を落ち着いた空間でお楽しみください。<br>
                </div>
            </div>


            <div class="row line_jp">
                <h2>ご予約は会員登録が必要になります。</h2>
                <%= link_to ' 予約をする', new_reservation_path, class: "btn label-default btn-wide" %>
            </div>


        </div>
    </div>
</div>

app/views/customer/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">


            <div class="row">
                <div class="top_image">

                    <%= image_tag asset_path("photo1.jpg") %>

                    <div>
                        <%= image_tag asset_path("photo2.jpg"), class: "slick" %>
                        <%= image_tag asset_path("photo3.jpg"), class: "slick" %>
                    </div>

                    <%= image_tag asset_path("photo4.jpg") %>

                    <div>
                        <%= image_tag asset_path("photo5.jpg"), class: "slick" %>
                        <%= image_tag asset_path("photo6.jpg"), class: "slick"  %>
                    </div>

                    <%= image_tag asset_path("photo7.jpg") %>

                </div>
            </div>




            <div class="row topics_prevention">
                <% if @topic.present? %>
                    <%= link_to "新型コロナウイルス等の感染予防対策について", topic_path(@topic.id), class:"prevention" %>
                <% end %>
            </div>


            <div class="title">TOPICS</div>
                <div class="row">
                    <div id="topics">
                        <div class="row top_topic">
                            <% @topics.first(6).each do |topic| %>

                                <%= link_to topic_path(topic.id) do %>
                                    <%= attachment_image_tag topic, :image, format: 'jpeg', size: "300x300",  fallback: "no_image.jpg"%><br>
                                    <p><%= topic.title %></p>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row more">
                <%= link_to "READ MORE", topics_path %>
            </div>


        </div>
    </div>
</div>

app/views/customer/homes/wedding.html.erb
<div class="container">
    <div class="row  text-color">


        <div class="row">
            <div class="wedding_image">
                <div class="style_wedding">Belle Foret Wedding</div>
            </div>
        </div>


        <div class="row line_jp">

            ここは、世界中の人々が一度は訪れてみたいと憧れる美食の殿堂。<br>
            高貴さとカジュアルモダン、その両方を同時に漂わせるラベンダーカラーの1階、<br>
            シャンパンゴールドとブラックの調和が華やかな気品を醸し出す２階ガストロノミー、<br>
            異なるダイニングルームでウエディングパーティを叶えることができる。<br>
            また、最上階にはクラシカルな雰囲気が漂う3つの部屋があり、ブライズルーム・親族控室・挙式スペースが完備されているのも魅力。<br>
            まるで、フランス貴族の館を思わせる気品あるインテリアや設えで、大切なゲストの皆様と、華やかで優雅な一日をお過ごしください。<br>


            世紀のシェフがプロデュースするフレンチ料理&スイーツで結婚式
            優れた料理人は、その人生の中で完結されたお皿を生み出す。
            だが誰しもが、作品とも呼べる料理を数多く持てる訳ではない。
            その奇跡に出会える場所で大切な一日を。

        </div>


        <div class="row line_jp">
            <h3>CONTACT</h3>
            <h4>
                詳細・お問い合わせ<br>
                お二人の理想のウェディングをサポートします。 まずはお問い合わせください。
            </h4>
        </div>


        <div class="row line_jp">
            <h2>ご予約は会員登録が必要になります。</h2>
            <%= link_to ' 予約をする', new_reservation_path, class: "btn label-default btn-wide" %>
        </div>


    </div>
</div>