config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, controllers: {
    sessions: "customer/devises/sessions",
    passwords: "customer/devises/passwords",
    registrations: "customer/devises/registrations",
  }


  devise_for :admins, controllers: {
    sessions: "admin/devises/sessions",
    passwords: "admin/devises/passwords",
    registrations: "admin/devises/registrations",
  }


  root 'customer/homes#top'


  get 'homes/about' => 'customer/homes#about', as: 'about'
  get 'homes/party' => 'customer/homes#party', as: 'party'
  get 'homes/wedding' => 'customer/homes#wedding', as: 'wedding'
  get 'inquiries/complete' => 'customer/inquiries#complete', as: 'inquiries_complete'
  post 'reservations/confirm' => 'customer/reservations#confirm', as: 'reservations_confirm'
  get 'reservations/complete' => 'customer/reservations#complete', as: 'reservations_complete'


  get 'admins/home/top' => 'admin/homes#top', as: 'admin_top'


  scope module: :customer do
    resources :customers, only: [:show, :edit, :update, :destroy]
    resources :reservations, only: [:new, :index, :create, :destroy]
    resources :topics, only: [:index, :show] do
  	  resource :favorites, only: [:create, :destroy]
  	  resources :comments, only: [:create, :destroy]
    end
  end


  namespace :admin do
    resources :topics, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :inquiries, only: [:index, :show]
    resources :reservations, only: [:index, :show]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/admin 2.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment 2.rb
class Comment < ApplicationRecord

  belongs_to :topic
  belongs_to :customer

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :topic
  belongs_to :customer

end

app/models/customer 2.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy


end

app/models/favorite 2.rb
class Favorite < ApplicationRecord

  belongs_to :topic
  belongs_to :customer

  validates_uniqueness_of :topic_id, scope: :customer_id


end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :topic
  belongs_to :customer

  validates_uniqueness_of :topic_id, scope: :customer_id


end

app/models/inquirie 2.rb
class Inquirie < ApplicationRecord

  belongs_to :admin

end

app/models/inquirie.rb
class Inquirie < ApplicationRecord

  belongs_to :admin

end

app/models/reservation.rb
class Reservation < ApplicationRecord


  belongs_to :customer
  belongs_to :admin


  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  validates :last_name_kana,  presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  validates :tel, presence: true, format: { with: /\A\d{10}$|^\d{11}\z/, message: '10桁か11桁の電話番号を入力してください。' }
  validates :email, presence: true
  validates :people, presence: true
  validates :date, presence: true


end

app/models/topic.rb
class Topic < ApplicationRecord


  belongs_to :admin


  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy


  attachment :image, destroy: false


  validates :title, presence: true, length: {maximum: 30, minimum: 2}
  validates :body, presence: true
  validates :image, presence: true


  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end


  def previous
    Topic.where("id < ?", self.id).order("id DESC").first
  end


  def next
    Topic.where("id > ?", self.id).order("id ASC").first
  end


end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController


  before_action :authenticate_admin!


  def new
    @topic = Topic.new
  end


  def index
    @topics = Topic.all.order(created_at: :desc)
    @topic = Topic.new
  end


  def show
    @topic = Topic.find(params[:id])
  end


  def edit
    @topic = Topic.find(params[:id])
  end


  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:notice] = "TOPICが変更されました。"
      redirect_to admin_topic_path(@topic.id)
    else
      render "edit"
    end
  end


  def create
    @topic = Topic.new(topic_params)
    @topic.admin_id = current_admin.id
    @topics = Topic.all
    if @topic.save!
      flash[:notice] = "TOPICが保存されました。"
      redirect_to admin_topic_path(@topic)
    else
      flash[:alert] = "再度入力してください。"
      render 'index'
    end
  end


  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to admin_topics_path
  end





  private

    def topic_params
      params.require(:topic).permit(:title, :body, :image, :admin_id)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_top_path
    when Customer
      root_path
    end
  end


  def after_sign_up_path_for(resource)
    case resource
    when Admin
      admin_top_path
    when Customer
      root_path
    end
  end


  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      new_customer_session_path
    end
  end





  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:is_enabled, :name, :email, :password])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name, ])
    end


end

app/controllers/customer/topics_controller.rb
class Customer::TopicsController < ApplicationController


  def index
  	@topic = Topic.new
    @topics = Topic.all.order(created_at: :desc).page(params[:page])
  end


  def show
  	@topics = Topic.find(params[:id])
  	@comment = Comment.new
  	@comments = @topics.comments
    @topic_new = Topic.new
  end


end

app/helpers/admin/homes_helper 2.rb
module Admin::HomesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/topics_helper 2.rb
module Admin::TopicsHelper
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/homes_helper 2.rb
module Customer::HomesHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/topics_helper.rb
module Customer::TopicsHelper
end

app/views/admin/topics/edit.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">

            <h2>TOPIC編集</h2>

            <%= form_for(@topic, url: admin_topic_path) do |f| %>

                <div class="field">
                    <%= f.label :Title %>
                    <%= f.text_field :title, autofocus: true, autocomplete: "title" %>
                </div>


                <div class="field">
                    <%= f.label :Text %>
                    <%= f.text_area :body, autofocus: true, autocomplete: "body" %>
                </div>


                <div class="field">
                    <%= f.label :image %>
		            <%= f.attachment_field :image %>
                </div>


                <div class="actions">
                    <%= f.submit "Update TOPIC" %>
                </div>


                <%= link_to "Show", admin_topic_path(@topic.id) %> |
                <%= link_to "Back", admin_topics_path %>

            <% end %>


        </div>
    </div>
</div>

app/views/admin/topics/index.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">


            <div class="row">
                <div class="col-xs-7">
                    <%= form_for(@topic,url:admin_topics_path) do |f| %>

                        <div class="field">
                            <%= f.label :image %>
                            <%= f.attachment_field :image %>
                        </div>


                        <div class="field">
                            <%= f.label :Title %>
                            <%= f.text_field :title, rows:'2', class: "form-control", placeholder: "Titleをここに" %>
                        </div>


                        <div class="field">
                            <%= f.label :Text %>
                            <%= f.text_area :body, rows:'5', class: "form-control", placeholder: "TEXTをここに" %>
                        </div>


                        <div class="actions">
                            <%= f.submit "Create TOPIC" %>
                        </div>

                    <% end %>
                </div>
            </div>


            <div class="row">
                <div class="topics">
                    <div class="col-sm-8">
                    <h2>TOPIC一覧</h2>
                    <div id="topics">
                        <% @topics.each do |topic| %>
                            <%= link_to admin_topic_path(topic.id) do %>
                                <%= attachment_image_tag topic, :image, format: 'jpeg', size: "150x150",  fallback: "no_image.jpg"%><br>
                                <p><%= topic.title %></p>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

app/views/admin/topics/show.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">


            <h2>TOPIC詳細</h2>

            <div class="row">
                <div id="topics">
                    <%= attachment_image_tag @topic, :image, format: 'jpeg', size: "150x150",  fallback: "no_image.jpg"%><br>
                    <%= @topic.title %>
                    <%= @topic.body %>
                    <%= link_to "Edit", edit_admin_topic_path(@topic.id) %>
			        <%= link_to "Destroy", admin_topic_path(@topic.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} %>
                </div>
            </div>


        </div>
    </div>
</div>