config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, controllers: {
    sessions: "customer/devises/sessions",
    passwords: "customer/devises/passwords",
    registrations: "customer/devises/registrations",
  }


  devise_for :admins, controllers: {
    sessions: "admin/devises/sessions",
    passwords: "admin/devises/passwords",
    registrations: "admin/devises/registrations",
  }


  root 'customer/homes#top'


  get 'homes/about' => 'customer/homes#about', as: 'about'
  get 'homes/party' => 'customer/homes#party', as: 'party'
  get 'homes/wedding' => 'customer/homes#wedding', as: 'wedding'
  get 'inquiries/complete' => 'customer/inquiries#complete', as: 'inquiries_complete'
  post 'reservations/confirm' => 'customer/reservations#confirm', as: 'reservations_confirm'
  get 'reservations/complete' => 'customer/reservations#complete', as: 'reservations_complete'


  get 'admins/home/top' => 'admin/homes#top', as: 'admin_top'


  scope module: :customer do
    resources :customers, only: [:show, :edit, :update, :destroy]
    resources :reservations, only: [:new, :index, :create, :destroy]
    resources :topics, only: [:index, :show] do
  	  resource :favorites, only: [:create, :destroy]
  	  resources :comments, only: [:create, :destroy]
    end
  end


  namespace :admin do
    resources :topics, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    resources :inquiries, only: [:index, :show]
    resources :reservations, only: [:index, :show]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy


end

app/models/topic.rb
class Topic < ApplicationRecord


  belongs_to :admin


  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy


  attachment :image, destroy: false


  validates :title, presence: true, length: {maximum: 30, minimum: 2}
  validates :body, presence: true
  validates :image, presence: true


  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end


  def previous
    Topic.where("id < ?", self.id).order("id DESC").first
  end


  def next
    Topic.where("id > ?", self.id).order("id ASC").first
  end


end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController


  before_action :authenticate_admin!


  def new
    @topic = Topic.new
  end


  def index
    @topics = Topic.all.order(created_at: :desc)
    @topic = Topic.new
  end


  def show
    @topic = Topic.find(params[:id])
  end


  def edit
    @topic = Topic.find(params[:id])
  end


  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:notice] = "TOPICが変更されました。"
      redirect_to admin_topic_path(@topic.id)
    else
      render "edit"
    end
  end


  def create
    @topic = Topic.new(topic_params)
    @topic.admin_id = current_admin.id
    @topics = Topic.all
    if @topic.save!
      flash[:notice] = "TOPICが保存されました。"
      redirect_to admin_topic_path(@topic)
    else
      flash[:alert] = "再度入力してください。"
      render 'index'
    end
  end


  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to admin_topics_path
  end





  private

    def topic_params
      params.require(:topic).permit(:title, :body, :image, :admin_id)
    end


end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController


  def create
  	topic = Topic.find(params[:topic_id])
    comment = current_customer.comments.new(comment_params)
    comment.topic_id = topic.id
    comment.save
    redirect_back(fallback_location: root_path)
  end


  def destroy
    @comment = Comment.find(params[:topic_id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end




  private

    def comment_params
      params.require(:comment).permit(:comment)
    end
    

    def correct_customer
      customer = Comment.find(params[:id])
      unless current_customer.id == customer.id
         redirect_to topic_path
      end
    end

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController


  def show
  	@customer = Customer.find(current_customer.id)
  end


  def edit
  	@customer = Customer.find(current_customer.id)
  end


  def update
  	@customer = Customer.find(current_customer.id)
    if @customer.update(customer_params)
      redirect_to customer_path
    else
      render :edit
    end
  end




  private

    def customer_params
      params.require(:customer).permit(:name, :email, :password)
    end



end

app/controllers/customer/devises/confirmations_controller.rb
# frozen_string_literal: true

class Customer::Devises::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/devises/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::Devises::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/devises/passwords_controller.rb
# frozen_string_literal: true

class Customer::Devises::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/devises/registrations_controller.rb
# frozen_string_literal: true

class Customer::Devises::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


  def show
  end


end

app/controllers/customer/devises/sessions_controller.rb
# frozen_string_literal: true

class Customer::Devises::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/devises/unlocks_controller.rb
# frozen_string_literal: true

class Customer::Devises::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController


  def create
  	topic = Topic.find(params[:topic_id])
    favorite = current_customer.favorites.new(topic_id: topic.id)
    favorite.save
    redirect_to topic_path(topic)
  end


  def destroy
  	topic = Topic.find(params[:topic_id])
    favorite = current_customer.favorites.find_by(topic_id: topic.id)
    favorite.destroy
    redirect_to topic_path(topic)
  end


end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController


  def top
  	@topic = Topic.find_by(title: "新型コロナウイルス等の感染予防対策について")
    @topics = Topic.all.order(created_at: :desc)
  end


end

app/controllers/customer/inquiries_controller.rb
class Customer::InquiriesController < ApplicationController


  before_action :authenticate_customer!


  def new
  end


  def create
  end


  def confirm
  end




  private

    def inquirie_params
      params.require(:inquirie).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :tel, :email, :body)
    end


end

app/controllers/customer/reservations_controller.rb
class Customer::ReservationsController < ApplicationController


  before_action :authenticate_customer!


  def new
    @reservation = Reservation.new
  end


  def index
  end


  def confirm
    @reservation = Reservation.new
  end


  def create
    @reservation = current_customer.reservations.create(reservation_params)
    if @reservation.save
      redirect_to reservations_complete_path
      flash[:notice] = "予約が完了しました。"
    else
      flash[:alert] = "再度入力してください"
      render :new
    end
  end


  def complete
  end




  private

    def reservation_params
      params.require(:reservation).permit(:customer_id, :first_name, :last_name, :first_name_kana, :last_name_kana, :tel, :email, :people, :date, :time, :body)
    end


end

app/controllers/customer/topics_controller.rb
class Customer::TopicsController < ApplicationController


  def index
  	@topic = Topic.new
    @topics = Topic.all.order(created_at: :desc).page(params[:page])
  end


  def show
  	@topics = Topic.find(params[:id])
  	@comment = Comment.new
  	@comments = @topics.comments
    @topic_new = Topic.new
  end


end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/customer/comments_helper 2.rb
module Customer::CommentsHelper
end

app/helpers/customer/comments_helper.rb
module Customer::CommentsHelper
end

app/helpers/customer/customers_helper 2.rb
module Customer::CustomersHelper
end

app/views/customer/topics/index.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">


            <div class="title">TOPICS</div>
                <div class="row">
                    <div id="topics">
                        <div class="row index_topic">
                            <% @topics.each do |topic| %>
                                <%= link_to topic_path(topic.id) do %>
                                    <%= attachment_image_tag topic, :image, format: 'jpeg', size: "300x300",  fallback: "no_image.jpg"%><br>
                                    <p><%= topic.title %></p>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
        	    <div class="paginate">
                    <%= paginate @topics %>
                </div>
            </div>


        </div>
    </div>
</div>

app/views/customer/topics/show.html.erb
<div class="container">
    <div class="row">
        <div class="text-color">


            <div class="row title">
                <h2>TOPICS</h2>
            </div>


            <div class="row">

                <div class="row image">
                    <%= attachment_image_tag @topics, :image, format: 'jpeg', size: "400x300",  fallback: "no_image.jpg" %>
                </div>


                <div class="row title ">
                    <%= @topics.title %>
                </div>


                <div class="row text ">
                    <%= @topics.body %>
                </div>

            </div>


            <div>
                <% if customer_signed_in? %>
                    <% if @topics.favorited_by?(current_customer) %>
                        <%= link_to topic_favorites_path(@topics), method: :delete do %>
                            <div class="glyphicon glyphicon-heart" aria-hidden="true" >
                                <%= @topics.favorites.count %>
                            </div>
                        <% end %>
                    <% else %>
                        <%= link_to topic_favorites_path(@topics), method: :post do %>
                            <div class="glyphicon glyphicon-heart" aria-hidden="true" >
                                <%= @topics.favorites.count %>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
            </div>


            <table class="table table-hover table-inverse">

                <div class= "row title">コメント</div>
                <table>
                    <% @comments.each do |comment| %>
                        <div class="col-sm-3">
                            <tr>

                                <td>
                                    <%= comment.customer.name %>
                                </td>

                                <td>
                                    <%= comment.comment %>
                                </td>

                                <td>
                                    <% if customer_signed_in? && comment.customer == current_customer %>
                                        <%= link_to "Destroy", topic_comment_path(comment), method: :delete, class: "btn btn-danger" %>
                                    <% end %>
                                </td>

                            </tr>
                        </div>
                    <% end %>
                </table>


                <% if customer_signed_in? %>
                <%= form_for [@topics, @comment] do |f| %>
                    <div class="row">
                        <div class="col-sm-12">
                            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                        </div>
        　              <%= f.submit "送信" %>
                    </div>
                <% end %>
                <% end %>

            </table>


            <div class="row page">

                <% if @topics.previous.present? %>
                    <%= link_to "PREV", topic_path(@topics.previous), class: "btn_arrow_back"%>
                <% end %>


                <%= link_to "LIST", topics_path %>


                <% if @topics.next.present? %>
                    <%= link_to "NEXT",topic_path(@topics.next), class: "btn_arrow" %>
                <% end %>

            </div>


        </div>
    </div>
</div>